Calamares

diff --git a/FOSS/airootfs/usr/local/bin/skel b/FOSS/airootfs/usr/local/bin/skel
--- a/FOSS/airootfs/usr/local/bin/skel
+++ b/FOSS/airootfs/usr/local/bin/skel
@@ -4,5 +4,11 @@ echo "#################################"
 echo "Moving content from skel"
 echo "#################################"
 
-for i in `ls /home/`; do su -s "/bin/bash" -c "cp -aT /etc/skel/ /home/$i/" $i || exit 0; done
+for dir in /home/*/; do
+  [[ -d "$dir" ]] || continue
+  user=$(basename "$dir")
+  echo "Copying skel to $user..."
+  su -s "/bin/bash" -c "cp -aT /etc/skel/ /home/$user/" "$user" || echo "Warning: Failed for $user"
+done
+
 rm /usr/local/bin/skel
